version: '1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - cluster.name=elasticsearch-introduction-cluster
      - node.name=elasticsearch-introduction-nodo
      - xpack.security.enabled=false
    ports:
      - '9200:9200/tcp'
    container_name: elasticsearch-introduction